"""Deterministic rendering of specs and patches.

Pure string-producing functions over the IR. **This module does not import
anything from the LLM/agent stack.** That isolation is the trust mechanism
for the chat loop: the spec echo and the diff the user sees before they
confirm a solve are computed by code, not generated by the model.

If the LLM gets these renderings, it should be downstream of solve and
clearly labeled as narration — not the trust handshake.
"""

from __future__ import annotations

from core.ir import (
    Box,
    Budget,
    Constraint,
    CVaRLimit,
    FactorExposure,
    GroupCap,
    LongOnly,
    MaxSharpe,
    MeanVariance,
    MinCVaR,
    MinTrackingError,
    MinVariance,
    Objective,
    PortfolioSpec,
    RiskParity,
    TrackingErrorCap,
    TransactionCost,
    TurnoverCap,
)


def _objective_phrase(obj: Objective) -> str:
    if isinstance(obj, MinVariance):
        return "Minimize variance (wᵀΣw)"
    if isinstance(obj, MeanVariance):
        return f"Mean-variance (min wᵀΣw − λμᵀw with λ = {obj.risk_aversion:g})"
    if isinstance(obj, MinCVaR):
        return f"Minimize CVaR at α = {obj.cvar_alpha:g}"
    if isinstance(obj, MaxSharpe):
        return f"Maximize Sharpe ratio (Charnes–Cooper, r_f = {obj.risk_free_rate:g})"
    if isinstance(obj, RiskParity):
        return "Risk parity (equal risk contribution, convex log-barrier)"
    if isinstance(obj, MinTrackingError):
        return f"Minimize tracking error vs {obj.benchmark}"
    raise AssertionError(f"Unknown objective kind: {type(obj).__name__}")


def _constraint_phrase(c: Constraint) -> str:
    if isinstance(c, Budget):
        return f"[{c.id}] Σw = {c.total:g}  (budget)"
    if isinstance(c, LongOnly):
        return f"[{c.id}] w ≥ 0  (long-only)"
    if isinstance(c, Box):
        scope = "all assets" if c.tickers is None else ", ".join(c.tickers)
        return (
            f"[{c.id}] {c.lower:g} ≤ w ≤ {c.upper:g}  on {scope}"
            f"  (box)"
        )
    if isinstance(c, GroupCap):
        floor = "" if c.min_weight is None else f"{c.min_weight:g} ≤ "
        return f"[{c.id}] {floor}Σw[{c.group}] ≤ {c.max_weight:g}  (group cap)"
    if isinstance(c, TurnoverCap):
        return f"[{c.id}] ‖w − w_prev‖₁ ≤ {c.max_turnover:g}  (turnover cap)"
    if isinstance(c, TransactionCost):
        return f"[{c.id}] {c.bps:g} bps · ‖w − w_prev‖₁  (transaction cost → objective penalty)"
    if isinstance(c, CVaRLimit):
        return f"[{c.id}] CVaR(α={c.alpha:g}) ≤ {c.max_cvar:g}  (CVaR limit)"
    if isinstance(c, TrackingErrorCap):
        return f"[{c.id}] TE vs {c.benchmark} ≤ {c.max_te:g}  (tracking-error cap)"
    if isinstance(c, FactorExposure):
        lo = "−∞" if c.min_exposure is None else f"{c.min_exposure:g}"
        hi = "+∞" if c.max_exposure is None else f"{c.max_exposure:g}"
        return f"[{c.id}] {lo} ≤ {c.factor}ᵀw ≤ {hi}  (factor exposure)"
    raise AssertionError(f"Unknown constraint kind: {type(c).__name__}")


def render_spec(spec: PortfolioSpec) -> str:
    """Plain-text confirmation block for the spec echo.

    Returns multi-line text. The chat loop wraps it in a Rich Panel; tests
    use the raw string to assert content (problem class, every constraint
    line, every objective phrase).
    """
    lines: list[str] = []
    lines.append("Truffle interpreted your request as follows.")
    lines.append("")
    lines.append(f"Universe   ({len(spec.universe)} tickers): {', '.join(spec.universe)}")
    lines.append(f"Objective  : {_objective_phrase(spec.objective)}")
    if spec.constraints:
        lines.append("Constraints:")
        for c in spec.constraints:
            lines.append(f"  • {_constraint_phrase(c)}")
    else:
        lines.append("Constraints: (none)")
    lines.append("")
    lines.append(f"Problem class: {spec.problem_class.upper()}")
    return "\n".join(lines)


def render_patch(
    patch: object,  # SpecPatch — typed loosely to avoid an import cycle with schema
    before: PortfolioSpec,
    after: PortfolioSpec,
) -> str:
    """Plain-text diff for a SpecPatch.

    Shows added constraints, removed constraint ids, and any objective swap.
    Universe swaps and override-dict changes are summarized one line each.
    """
    # Local import to avoid a load-order dep between schema and render
    # (schema imports from core.ir; render imports neither schema nor agent.*).
    from agent.schema import SpecPatch  # noqa: PLC0415

    if not isinstance(patch, SpecPatch):
        raise TypeError(f"render_patch expects SpecPatch, got {type(patch).__name__}")

    lines: list[str] = ["Truffle applied this amendment to your spec."]
    if patch.replace_objective is not None:
        lines.append(
            f"  • Objective: {_objective_phrase(before.objective)} → "
            f"{_objective_phrase(after.objective)}"
        )
    for cid in patch.remove_constraint_ids:
        lines.append(f"  • Removed constraint: {cid}")
    for c in patch.add_constraints:
        lines.append(f"  • Added constraint: {_constraint_phrase(c)}")
    if patch.set_universe is not None:
        lines.append(
            f"  • Universe: {len(before.universe)} → {len(after.universe)} tickers "
            f"({', '.join(after.universe)})"
        )
    if patch.estimation_overrides:
        lines.append(f"  • Estimation overrides: {patch.estimation_overrides}")
    if patch.backtest_overrides:
        lines.append(f"  • Backtest overrides: {patch.backtest_overrides}")
    lines.append("")
    lines.append(f"Problem class is now: {after.problem_class.upper()}")
    return "\n".join(lines)
