"""Deterministic rendering of specs and patches.

Pure string-producing functions over the IR. **This module does not import
anything from the LLM/agent stack.** That isolation is the trust mechanism
for the chat loop: the spec echo and the diff the user sees before they
confirm a solve are computed by code, not generated by the model.

If the LLM gets these renderings, it should be downstream of solve and
clearly labeled as narration — not the trust handshake.
"""

from __future__ import annotations

from core.ir import (
    Box,
    Budget,
    Cardinality,
    Constraint,
    CVaRLimit,
    FactorExposure,
    GroupCap,
    LongOnly,
    MaxSharpe,
    MeanVariance,
    MinCVaR,
    MinTrackingError,
    MinVariance,
    Objective,
    PortfolioSpec,
    RiskParity,
    TrackingErrorCap,
    TransactionCost,
    TurnoverCap,
)


def _objective_phrase(obj: Objective) -> str:
    if isinstance(obj, MinVariance):
        return "Minimize variance (wᵀΣw)"
    if isinstance(obj, MeanVariance):
        return f"Mean-variance (min wᵀΣw − λμᵀw with λ = {obj.risk_aversion:g})"
    if isinstance(obj, MinCVaR):
        return f"Minimize CVaR at α = {obj.cvar_alpha:g}"
    if isinstance(obj, MaxSharpe):
        return f"Maximize Sharpe ratio (Charnes–Cooper, r_f = {obj.risk_free_rate:g})"
    if isinstance(obj, RiskParity):
        return "Risk parity (equal risk contribution, convex log-barrier)"
    if isinstance(obj, MinTrackingError):
        return f"Minimize tracking error vs {obj.benchmark}"
    raise AssertionError(f"Unknown objective kind: {type(obj).__name__}")


def _constraint_phrase(c: Constraint) -> str:
    if isinstance(c, Budget):
        return f"[{c.id}] Σw = {c.total:g}  (budget)"
    if isinstance(c, LongOnly):
        return f"[{c.id}] w ≥ 0  (long-only)"
    if isinstance(c, Box):
        scope = "all assets" if c.tickers is None else ", ".join(c.tickers)
        return (
            f"[{c.id}] {c.lower:g} ≤ w ≤ {c.upper:g}  on {scope}"
            f"  (box)"
        )
    if isinstance(c, GroupCap):
        floor = "" if c.min_weight is None else f"{c.min_weight:g} ≤ "
        return f"[{c.id}] {floor}Σw[{c.group}] ≤ {c.max_weight:g}  (group cap)"
    if isinstance(c, TurnoverCap):
        return f"[{c.id}] ‖w − w_prev‖₁ ≤ {c.max_turnover:g}  (turnover cap)"
    if isinstance(c, TransactionCost):
        return f"[{c.id}] {c.bps:g} bps · ‖w − w_prev‖₁  (transaction cost → objective penalty)"
    if isinstance(c, CVaRLimit):
        return f"[{c.id}] CVaR(α={c.alpha:g}) ≤ {c.max_cvar:g}  (CVaR limit)"
    if isinstance(c, TrackingErrorCap):
        return f"[{c.id}] TE vs {c.benchmark} ≤ {c.max_te:g}  (tracking-error cap)"
    if isinstance(c, FactorExposure):
        lo = "−∞" if c.min_exposure is None else f"{c.min_exposure:g}"
        hi = "+∞" if c.max_exposure is None else f"{c.max_exposure:g}"
        return f"[{c.id}] {lo} ≤ {c.factor}ᵀw ≤ {hi}  (factor exposure)"
    if isinstance(c, Cardinality):
        floor = "" if c.min_names is None else f"{c.min_names} ≤ "
        dust = "" if c.min_position is None else f", w_held ≥ {c.min_position:g}"
        return (
            f"[{c.id}] {floor}#holdings ≤ {c.max_names}{dust}  "
            "(cardinality — makes this a mixed-integer problem)"
        )
    raise AssertionError(f"Unknown constraint kind: {type(c).__name__}")


def _constraint_phrase_with_policy(c: Constraint) -> str:
    """Render the constraint plus any user-declared diagnosis policy."""

    phrase = _constraint_phrase(c)
    if c.elastic is False and type(c).elastic_default:
        return f"{phrase}  [non-negotiable during diagnosis]"
    return phrase


def render_spec(spec: PortfolioSpec) -> str:
    """Plain-text confirmation block for the spec echo.

    Returns multi-line text. The chat loop wraps it in a Rich Panel; tests
    use the raw string to assert content (problem class, every constraint
    line, every objective phrase).
    """
    lines: list[str] = []
    lines.append("Truffle interpreted your request as follows.")
    lines.append("")
    lines.append(f"Universe   ({len(spec.universe)} tickers): {', '.join(spec.universe)}")
    lines.append(f"Objective  : {_objective_phrase(spec.objective)}")
    if spec.constraints:
        lines.append("Constraints:")
        for c in spec.constraints:
            lines.append(f"  • {_constraint_phrase_with_policy(c)}")
    else:
        lines.append("Constraints: (none)")
    lines.append("")
    lines.append(f"Problem class: {spec.problem_class.upper()}")
    if spec.problem_class == "mip":
        lines.extend(_mip_advisory(spec))
    return "\n".join(lines)


def _mip_advisory(spec: PortfolioSpec) -> list[str]:
    """Warn — before solving — that this is a mixed-integer problem.

    Names the constraint that forced integrality, flags the longer solve, and
    sets the expectation that shadow prices will be conditional on the selected
    names. The chat loop appends a universe-size guard line on top of this when
    the search space looks large.
    """
    causes = [
        _constraint_phrase_with_policy(c)
        for c in spec.constraints
        if type(c).problem_class_impact == "mip"
    ]
    cause_line = causes[0] if causes else "a mixed-integer constraint"
    return [
        "",
        "⚠ This is a MIXED-INTEGER problem — caused by:",
        f"    {cause_line}",
        "  • It is solved by a mixed-integer solver (HiGHS for MILP, SCIP for",
        "    MIQP/MISOCP), which can take noticeably longer than a convex solve.",
        "  • Sensitivities, when available, are CONDITIONAL on the selected names",
        "    (computed by fixing the selection and re-solving), not global.",
        "    Time-limited or mismatched conditional portfolios report them unavailable.",
    ]


def render_patch(
    patch: object,  # SpecPatch — typed loosely to avoid an import cycle with schema
    before: PortfolioSpec,
    after: PortfolioSpec,
) -> str:
    """Plain-text diff for a SpecPatch.

    Shows added constraints, removed constraint ids, and any objective swap.
    Universe swaps and override-dict changes are summarized one line each.
    """
    # Local import to avoid a load-order dep between schema and render
    # (schema imports from core.ir; render imports neither schema nor agent.*).
    from agent.schema import SpecPatch  # noqa: PLC0415

    if not isinstance(patch, SpecPatch):
        raise TypeError(f"render_patch expects SpecPatch, got {type(patch).__name__}")

    lines: list[str] = ["Truffle applied this amendment to your spec."]
    if patch.replace_objective is not None:
        lines.append(
            f"  • Objective: {_objective_phrase(before.objective)} → "
            f"{_objective_phrase(after.objective)}"
        )
    for cid in patch.remove_constraint_ids:
        lines.append(f"  • Removed constraint: {cid}")
    for c in patch.add_constraints:
        lines.append(f"  • Added constraint: {_constraint_phrase_with_policy(c)}")
    if patch.set_universe is not None:
        lines.append(
            f"  • Universe: {len(before.universe)} → {len(after.universe)} tickers "
            f"({', '.join(after.universe)})"
        )
    if patch.estimation_overrides:
        lines.append(f"  • Estimation overrides: {patch.estimation_overrides}")
    if patch.backtest_overrides:
        lines.append(f"  • Backtest overrides: {patch.backtest_overrides}")
    lines.append("")
    lines.append(f"Problem class is now: {after.problem_class.upper()}")
    return "\n".join(lines)
